### ISSUE TITLE
Conflicts with MooTools implementation of window.getSize()

### ISSUE THREAD

**Issue by Bilge** [desandro/get-size#1]
MooTools implements a version of window.getSize that returns the window dimensions when passed no parameters. Loading this library after MooTools causes it to overwrite MooTool's implementation of window.getSize and any scripts that rely on it to fail.

---

_From @desandro:_

**+1** this issue if you would like to see it resolved.

**Comment by fritzmg** [comment]
The fix works (replacing all instances of `getSize` with something else, like `getSize_FIXME`). However, it would be nice if this finally fixed in the source of Masonry.js it's been far over a year now since it was first reported ;).

Since I am using the Contao CMS I find myself confronted with this problem frequently whenever I want to use Masonry.js there, since a lot of other Contao Extensions rely on MooTools.

**Comment by Bilge** [comment]
I'm pretty sure @desandro doesn't give a single shit about MooTools at this point.

**Comment by hamidrezabstn** [comment]
please clear out how to fix this problem!!! i am a user not a professional! i've tried find/replace trick but it did not work ! please HHHHHHHHHHHHEEEEEEEEEEELLLLLLLLLLLPPPPPPPPPPPP!!!

**Comment by danyj** [comment]
well , no matter where the discussion is , 2 years after the report of this bug it is not changed, I took @nicbell advice and fixed it but you can just name your getSize something else and close this issue.

**Comment by Bilge** [comment]
I already tried closing this once but Desandro was like, *NIET*.

**Comment by fritzmg** [comment]
Well, why close it, when it's not resolved yet?

**Comment by desandro** [comment]
This issue is still open because it is not resolved. getSize is a lower-level library [used in many of my other libraries](https://www.npmjs.com/browse/depended/get-size). I prefer to keep the  browser global name as `getSize` rather than changing it for several reasons:

+ Likely backwards compatibility issues, requiring updates to 
+ After changing the browser global from `window.getSize`, There'd be a name mis-match with the project on GitHub `desandro/get-size` and the npm library [`get-size`](https://www.npmjs.com/package/get-size). It's either confusing, or I have to switch over names
+ This issue has not gained much public attention

I do give several shits about Moo Tools. I also care about other libraries. I am considering getSize's interoperability within the huge front-end development ecosystem. As this issue has only had a handful of replies in 2 years, this issue's solution hasn't warranted priority over maintaining the projects current compatibility.

**Comment by mthomsonnz** [comment]
Currently I'm also having a problem with this issue. Within the joomla cms ecosystem (5 million+ sites) the mootools library is still used a lot, and any template that implements isotope will clash with any joomla extension that uses mootools, so +1 for please fix this! Thanks.

**Comment by websperations** [comment]
I am also having this issue with Joomla.  I am using a commercial template on a site upgrade and now our existing Ignite Photo Gallery lightbox functionality is broken.  Ignite Gallery developers isolated this problem and basically said they cannot address the issue as it's a js file.

**Comment by AbcAeffchen** [comment]
:+1: for fixing this issue

**Comment by AnrietteC** [comment]
Thanks nicbell! I hate having to edit plugins like this, but it breaks some K2 front-end editing.

**Comment by starlingDesign** [comment]
+1 on the issue.  I just loaded MooTools after Masonry (which contains this same code) and my MooTools dependent stuff works fine.

**Comment by rettenbs** [comment]
+1

**Comment by desandro** [comment]
Putting this one to rest. If you are using MooTools and a Metafizzy plugin in 2022, you are incredible. Goodnight.
